---
# Get OSP Server Instance Information
- name: OpenStack servers
  os_server_facts:
    cloud: ospcloud
  register: ospname

# - debug:
#     var: ospname.ansible_facts.openstack_servers

# - name: Print records  
#   debug:
#     var: item.name 
#   with_items: 
#     - "{{ ospname.ansible_facts.openstack_servers }}"

# Remove OSP Instances
- name: Remove Openstack Server Instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
    image: rhel-guest
    flavor: m2.small
    delete_fip: true
  with_items: 
  - "{{ ospname.ansible_facts.openstack_servers }}"
