---
# tasks file for myvhost
- name: install httpd packages
  yum:
    name: httpd
    state: latest
- name: start httpdi service
  service:
    name: httpd
    state: started
    enabled: true
- name: install html content of vhost
  copy:
    src: html/ 
    dest: "/var/www/vhosts/{{ ansible_hostname }}"
- name: create vhost config file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
