---
# Set up public/private key pairs to protect the instance at launch time
# Public/private key pairs work by keeping the public key on the instance and the private key on your local workstation
- name: Create ssh keypair for "{{ ansible_env.USER }}"
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa

- name: Use public key of user "{{ ansible_env.USER }}" to connect to OpenStack
  os_keypair:
    cloud: ospcloud
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  register: key
