---
- name: install tomcat
  yum:
    name: tomcat
    state: latest

- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: create tomcat web directory {{ tomcat_webapps_root }}
  file:
    path: "{{ tomcat_webapps_root }}"
    state: directory

- name: copy index.html to {{ tomcat_webapps_root }}
  template:
    src: index.html.j2
    dest: "{{ tomcat_webapps_root }}/index.html"
    mode: 0644

- name: start tomcat
  service:
    name: tomcat
    state: started

- name: install apache
  yum:
    name: httpd
    state: latest
    
- name: start and enable apache at boot
  service:
    name: httpd
    state: started
    enabled: yes
