---
- name: test facts
  hosts: all
  tasks:
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result
  - name: debug result
    debug:
      var: result

