---
- name: playbook
  hosts: webservers

  tasks:

    - block:
      - name: install packages
        include: install_packages.yml
        vars:
          memory: 256
          web_package: httpd
          ssl_package: mod_ssl
          web_service: httpd
      - name: configure web page
        include: configure_web.yml
        vars:
          https_uri: http://materials.example.com/task_control/https.conf
          ssl_uri: http://materials.example.com/task_control/ssl.tar.gz
      - name: configure firewall
        include: configure_firewall.yml
        vars:
          fw_package: firewalld
          fw_service: firewalld
        tags: production
    
      rescue:
      - name: install webserver manually
        yum:
          name: httpd
          state: latest
        notify: restart_services
      - name: debug message
        debug:
          msg: "Failed to import and run all the tasks; installing the web server manually"

      always:
      - name: get status httpd service
        shell:
          cmd: "systemctl status httpd"

  handlers:
  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - httpd
      - firewalld   

      
