---
# Run smoke test for 3 tier app on OpenStack instances
- name: Fetch instance info for Openstack frontend instances
  os_server_facts:
    cloud: ospcloud
    server: frontend
  register: result
  when: ansible_product_name == 'OpenStack Compute'

- name: Check loadbalancer instances on Openstack instances
  uri:
    url: "http://{{item.accessIPv4}}"
    return_content: yes
  with_items: "{{result.ansible_facts.openstack_servers}}"
  when: ansible_product_name == 'OpenStack Compute'
  register: result
  until: '"Tomcat on app" in result.content'
  retries: 10
  delay: 1

# todo: add AWS ansible_product_name for 'normal' and prod instance homework?
- name: Check loadbalancer instances            
  uri:
    url:  http://frontend1.{{ GUID }}.example.opentlc.com
    return_content: yes
  register: result
  until: '"Tomcat on app" in result.content'
  retries: 10
  delay: 1

