---
- name: install {{ payload }}
  yum:
    name: "{{ payload }}"
    state: latest
  tags:
    - apps

- name: enable {{ payload }} at boot
  service:
    name: "{{ payload }}"
    enabled: yes
  tags:
    - apps

- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
  tags:
    - apps

- name: copy index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644
  tags:
    - apps

- name: restart tomcat
  service:
    name: "{{ payload }}"
    state: restarted
  tags:
    - apps
